# Generated by Django 4.2 on 2023-04-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='domicile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.domicile'),
        ),
    ]
